import {StyleSheet, Color} from 'react-native';
import {
  fontRef,
  fullWidth,
  heightRef,
  widthRef,
} from '../../../Constant/screenSize';
import {theme} from '../../../Core/Theme';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: theme.secondary},
  aboutstyle: {
    fontSize: 25,
    color: '#1D1717',
    paddingTop: 40,
  },
  headerCard: {
    width: fullWidth - 30 * widthRef,
    marginHorizontal: 15 * widthRef,
    marginTop: 10 * heightRef,
    borderRadius: 5 * fontRef,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  card: {
    margin: 9 * heightRef,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    borderRadius: 5 * fontRef,
  },
  saperater: {
    // width: getWidth(8),
  },
  Poster: {
    // height: getHeight(85),
    // width: getWidth(93),
    // backgroundColor: 'red',
    borderRadius: 5,
    alignSelf: 'center',
    marginTop: 10,
  },
  headerimage: {
    // height: getHeight(40),
    // width: getWidth(100),
    // backgroundColor: 'red',
    borderRadius: 20,
    width: '99%',
    // flexDirection: 'row',
    height: 170 * heightRef,
    marginHorizontal: 10 * widthRef,
    justifyContent: 'space-around',
    alignSelf: 'center',
    alignItems: 'center',
    margin: 10 * heightRef,
  },
  backimage1: {
    // height: getHeight(25),
    // width: getWidth(30),
    width: '90%',
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    height: 190 * heightRef,
  },
  detailtext: {fontSize: 18, fontWeight: 'bold', color: 'white'},
  movieText: {
    fontSize: 26,
    fontWeight: 'bold',
    marginTop: 90,
    color: 'white',
    textDecorationLine: 'underline',
  },
  Tvtext: {
    fontWeight: 'bold',
    color: theme.white,
    textAlign: 'center',
    fontFamily: theme.fontFamily,
    marginHorizontal: 10 * widthRef,
    fontSize: 24 * fontRef,
  },
  seeAll: {
    fontWeight: 'bold',
    color: 'grey',
    textAlign: 'center',
    textTransform: 'uppercase',
    fontFamily: theme.fontFamily,
    marginHorizontal: 10 * widthRef,
    fontSize: 16 * fontRef,
  },
  // headerview: {height: getHeight(70)},
  textview: {marginTop: 390},
  contaner: {flex: 1},
  linearGradient: {
    // height: getHeight(42),
    // width: getWidth(95),
    marginTop: 230.5,
    padding: 20,
  },
  headerview: {
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    padding: 10,
  },
  logotext: {fontSize: 17, fontWeight: 'bold', color: '#FFF'},
  cardfotter: {
    // height: getHeight(10),
    backgroundColor: '#1A5276',
    borderBottomStartRadius: 5,
    borderBottomEndRadius: 5,
  },
  button: {
    width: '30%',
    height: 40 * heightRef,
    justifyContent: 'center',
    borderWidth: 1,
    elevation: 10,
    borderColor: theme.primary,
    alignItems: 'center',
    borderRadius: 5 * heightRef,
    backgroundColor: theme.primary,
  },
  btntext: {
    fontWeight: '700',
    color: theme.white,
    textAlign: 'center',
    fontFamily: theme.fontFamily,
    marginHorizontal: 10 * widthRef,
    fontSize: 16 * fontRef,
  },
  name: {
    fontWeight: '900',
    color: 'white',
    elevation: 30,
    textAlign: 'center',
    fontFamily: 'arlrdbd',
    marginHorizontal: 18 * widthRef,
    marginTop: 15 * fontRef,
    textTransform: 'uppercase',
    fontSize: 24 * fontRef,
  },
  movieName: {
    fontWeight: '900',
    color: 'white',
    marginBottom: 10 * fontRef,
    alignSelf: 'flex-end',
    textTransform: 'uppercase',
    fontFamily: theme.fontFamily,

    fontSize: 16 * fontRef,
  },
  checkbox: {
    position: 'absolute',
    top: -8,

    borderRadius: 5 * fontRef,
    right: -8,
    borderColor: theme.primary,
    height: 35 * heightRef,
    width: 35 * widthRef,
    borderWidth: 1,
  },
});
